/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    ChartGraph: typeof import('./components/ChartGraph.vue')['default']
    CurrencyInput: typeof import('./components/CurrencyInput.vue')['default']
    ExchangeRateCard: typeof import('./components/ExchangeRateCard.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    LoadingSpinner: typeof import('./components/LoadingSpinner.vue')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsPanel: typeof import('./components/SettingsPanel.vue')['default']
    ThemeToggle: typeof import('./components/ThemeToggle.vue')['default']
  }
}
